services:
  - type: web
    name: event-budget-backend
    env: python
<<<<<<< HEAD
    region: oregon
    plan: free
=======
>>>>>>> b944286 (commit)
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
<<<<<<< HEAD
    rootDir: backend
=======
    plan: free
    region: oregon
    rootDir: backend

  - type: web
    name: event-budget-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars: []
    plan: free
    region: oregon
    rootDir: src
>>>>>>> b944286 (commit)
