services:
  - type: web
    name: event-budget-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    rootDir: backend

  - type: web
    name: event-budget-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars: []
    plan: free
    region: oregon
    rootDir: src
      - type: web
    name: event-budget-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    plan: free
    rootDir: frontend
